export const themes: string[] = [
  'dark',
  'light',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'black',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
  'dim',
  'nord',
  'sunset',
];

export const tableClassname = {
  table:
    'w-full min-w-[1373px] border-collapse border border-base-content/50 text-sm',
  th: 'h-20 py-2 px-4 border border-base-content/10 text-sm font-normal text-base-content/80',
  td: 'h-auto py-2 px-4 border border-base-content/10 text-sm font-normal text-base-content/80 text-center',
};
